AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  micromobility-app

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Resources:

  SnapshotGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: snapshot-get/
      Handler: app.lambdaHandler
      Events:
        Snapshot:
          Type: Api
          Properties:
            Path: /snapshot
            Method: get
      Environment:
        Variables:
          BUCKET_NAME: !Ref SnapshotBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SnapshotBucket
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  SnapshotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub micromobility-snapshots
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SnapshotProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: snapshot-processor/
      MemorySize: 1024
      Handler: app.lambdaHandler
      Environment:
        Variables:
          BUCKET_NAME: !Ref SnapshotBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref SnapshotBucket
        - S3ReadPolicy:
            BucketName: !Ref SnapshotBucket
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  HourlySnapshotSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: hourly-snapshot-schedule
      ScheduleExpression: cron(0 * * * ? *)
      ScheduleExpressionTimezone: America/New_York
      StartDate: "2025-04-14T22:00:00.000Z"
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt SnapshotProcessorFunction.Arn
        RoleArn: !GetAtt SchedulerInvokeRole.Arn

  SchedulerInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowInvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt SnapshotProcessorFunction.Arn

  SnapshotBackfillQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: snapshot-backfill-queue
      VisibilityTimeout: 900

  SnapshotBackfillFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: snapshot-backfill-function
      CodeUri: snapshot-backfill/
      Handler: app.lambdaHandler
      Timeout: 900
      MemorySize: 1024
      ReservedConcurrentExecutions: 100
      Environment:
        Variables:
          BUCKET_NAME: !Ref SnapshotBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SnapshotBucket
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        BackfillQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SnapshotBackfillQueue.Arn
            BatchSize: 5
            Enabled: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub micromobility-static-geo
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET]
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"

  StaticAssetsOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: static-assets-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  StaticAssetsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: "CDN for static geo assets (roadblocks, metro, h3 grid)"
        DefaultRootObject: ""
        Origins:
          - Id: StaticAssetsOrigin
            DomainName: !GetAtt StaticAssetsBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref StaticAssetsOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: StaticAssetsOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
        PriceClass: PriceClass_100

  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${StaticAssetsBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${StaticAssetsDistribution}"

Outputs:
  SnapshotApi:
    Description: "API Gateway endpoint URL for Prod stage snapshot endpoints"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/snapshot/"

  SnapshotGetFunction:
    Description: "SnapshotGet Lambda Function ARN"
    Value: !GetAtt SnapshotGetFunction.Arn

  SnapshotGetFunctionIamRole:
    Description: "Implicit IAM Role created for SnapshotGet function"
    Value: !GetAtt SnapshotGetFunctionRole.Arn

  SnapshotBucketName:
    Description: "S3 bucket for storing snapshot JSONs (private)"
    Value: !Ref SnapshotBucket

  SnapshotProcessorFunctionArn:
    Description: "Lambda that fetches, processes, and stores snapshots"
    Value: !GetAtt SnapshotProcessorFunction.Arn

  SnapshotBackfillQueueUrl:
    Description: "SQS queue for snapshot backfill"
    Value: !Ref SnapshotBackfillQueue

  StaticAssetsBucketName:
    Description: "S3 bucket for static geo files (roadblocks, metro, h3 grid)"
    Value: !Ref StaticAssetsBucket

  StaticAssetsCdnDomain:
    Description: "CloudFront domain for static geo assets"
    Value: !GetAtt StaticAssetsDistribution.DomainName
